services:
  postgres:
    image: postgres:17
    restart: always
    user: postgres
    secrets:
      - pg-password
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tododb
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg-password
    ports:
      - 5432:5432
    networks:
      - dbnet
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    image: sample-todo:latest
    ports:
      - 3000:3000
    networks:
      - dbnet
    environment:
      - NODE_ENV=production
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg-data:

secrets:
  pg-password:
    file: pg/pass.txt

networks:
  dbnet: